# permissions for end users to edit klovercloudfacades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudfacade-editor-role
rules:
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudfacades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudfacades/status
  verbs:
  - get
