# permissions for end users to edit klovercloudpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudpipeline-editor-role
rules:
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines/status
  verbs:
  - get
