# permissions for end users to edit klovercloudmanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudmanagement-editor-role
rules:
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudmanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudmanagements/status
  verbs:
  - get
