# permissions for end users to view klovercloudpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudpipeline-viewer-role
rules:
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines/status
  verbs:
  - get
