
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudfacades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudfacades/finalizers
  verbs:
  - update
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudfacades/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudmanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudmanagements/finalizers
  verbs:
  - update
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudmanagements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - service.klovercloud.com
  resources:
  - klovercloudpipelines/status
  verbs:
  - get
  - patch
  - update
