// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudFacade) DeepCopyInto(out *KlovercloudFacade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudFacade.
func (in *KlovercloudFacade) DeepCopy() *KlovercloudFacade {
	if in == nil {
		return nil
	}
	out := new(KlovercloudFacade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudFacade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudFacadeList) DeepCopyInto(out *KlovercloudFacadeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlovercloudFacade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudFacadeList.
func (in *KlovercloudFacadeList) DeepCopy() *KlovercloudFacadeList {
	if in == nil {
		return nil
	}
	out := new(KlovercloudFacadeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudFacadeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudFacadeSpec) DeepCopyInto(out *KlovercloudFacadeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudFacadeSpec.
func (in *KlovercloudFacadeSpec) DeepCopy() *KlovercloudFacadeSpec {
	if in == nil {
		return nil
	}
	out := new(KlovercloudFacadeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudFacadeStatus) DeepCopyInto(out *KlovercloudFacadeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudFacadeStatus.
func (in *KlovercloudFacadeStatus) DeepCopy() *KlovercloudFacadeStatus {
	if in == nil {
		return nil
	}
	out := new(KlovercloudFacadeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudManagement) DeepCopyInto(out *KlovercloudManagement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudManagement.
func (in *KlovercloudManagement) DeepCopy() *KlovercloudManagement {
	if in == nil {
		return nil
	}
	out := new(KlovercloudManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudManagement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudManagementList) DeepCopyInto(out *KlovercloudManagementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlovercloudManagement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudManagementList.
func (in *KlovercloudManagementList) DeepCopy() *KlovercloudManagementList {
	if in == nil {
		return nil
	}
	out := new(KlovercloudManagementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudManagementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudManagementSpec) DeepCopyInto(out *KlovercloudManagementSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudManagementSpec.
func (in *KlovercloudManagementSpec) DeepCopy() *KlovercloudManagementSpec {
	if in == nil {
		return nil
	}
	out := new(KlovercloudManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudManagementStatus) DeepCopyInto(out *KlovercloudManagementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudManagementStatus.
func (in *KlovercloudManagementStatus) DeepCopy() *KlovercloudManagementStatus {
	if in == nil {
		return nil
	}
	out := new(KlovercloudManagementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudPipeline) DeepCopyInto(out *KlovercloudPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudPipeline.
func (in *KlovercloudPipeline) DeepCopy() *KlovercloudPipeline {
	if in == nil {
		return nil
	}
	out := new(KlovercloudPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudPipelineList) DeepCopyInto(out *KlovercloudPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlovercloudPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudPipelineList.
func (in *KlovercloudPipelineList) DeepCopy() *KlovercloudPipelineList {
	if in == nil {
		return nil
	}
	out := new(KlovercloudPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlovercloudPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudPipelineSpec) DeepCopyInto(out *KlovercloudPipelineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudPipelineSpec.
func (in *KlovercloudPipelineSpec) DeepCopy() *KlovercloudPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(KlovercloudPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlovercloudPipelineStatus) DeepCopyInto(out *KlovercloudPipelineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlovercloudPipelineStatus.
func (in *KlovercloudPipelineStatus) DeepCopy() *KlovercloudPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(KlovercloudPipelineStatus)
	in.DeepCopyInto(out)
	return out
}
